name: xolera
description: A new Flutter project.

version: 2.5.3+1

environment:
  sdk: ">=2.5.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^0.23.0
  http: ^0.13.4
  flutter_session: ^0.1.1
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  
  
flutter_icons:
  image_path: "assets/images/CatLogo.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  
           
                